### PR TITLE
Fix/tty

### PR DESCRIPTION
**Pull request by sammygriffiths**
Was running into issues with STDIN being detected as a TTY in docker when it wasn't. This is a more reliable way of checking and appears to solve the issue.

### CODE REVIEW

**Comment by timrspratt** [comment]
It was based on https://github.com/laravel/installer/blob/master/src/NewCommand.php

**Comment by sammygriffiths** [comment]
@andrewnclark Yep from my manual testing. When my automated test plan comes to fruition functionality should be tested at the same time styleci does its thing, but for now manual testing will have to do.

**Comment by timrspratt** [comment]
Also exits in RunComposerScripts class

**Comment by andrewnclark** [comment]
> @andrewnclark Yep from my manual testing. When my automated test plan comes to fruition functionality should be tested at the same time styleci does its thing, but for now manual testing will have to do.

Do I get to use my github actions access? I need to setup some stuff on my fork but haven't got round to it yet!

**Pull request merged**
